### ISSUE TITLE
Feature request: Introduce DataSharedFacetValue and MethodSharedFacetValue subtypes

### ISSUE THREAD

**Issue by xaviervia** [Mojang/ore-ui#113]
Moving forward, we don't want to mix and match methods and data in shared facets. We want to think of data facets as pure data, much like Redux state, and method facet as flat lists of available API calls from the remote.

Additionally, `MethodSharedFacetValue`s could automatically do a `.bind` on the methods it includes, to avoid issues with selecting individual methods from the facet and losing the `this` reference.

**Comment by pirelenito** [comment]
Closing this as we are exploring better alternative APIs for shared facets.
