### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by frayray909090** [Mojang/ore-ui#57]
Can I help with coding make me member please I love coding

**Comment by xaviervia** [comment]
Hello @frayray909090!

First of all, sorry for the very late reply. This repository is quite new and we haven’t actively monitored comments from outside the team, but we should have!

To your question, you are welcome to contribute! This repository is open source, so you are totally able to fork and modify, and then pull request back your contribution. Github has a pretty good guide on how to do this https://docs.github.com/en/get-started/quickstart/contributing-to-projects . You don’t need special access to be able to contribute :slightly_smiling_face:

Hope this helps! I’ll close the issue, but you can comment more if you have more questions
Cheers

@xaviervia

**Comment by frayray909090** [comment]
Well then hello @xaviervia!

I just want more info but also sorry for my language 

but why the fuck did you guys and report system and filter to java? because I breaks anarchy servers like 2b2t but it makes more sense on mobile little kid will be on mobile like 16 and up play java because little kids won’t wait for a pc so they can only get a mobile device

**Comment by xaviervia** [comment]
Hey @frayray909090!

We're happy to see your passion and suggestions for Minecraft, though this is not quite the right forum for that :)

This project, `ore-ui`, is an open source project related to UI development. To ask questions or make suggestion about the game, check out the official Minecraft bug tracker.

Here's the bug tracker for Java: https://bugs.mojang.com/projects/MC/issues/

Here's the bug tracker for Bedrock: https://bugs.mojang.com/projects/MCPE/issues/

Cheers, and thank you again for the interest!
