### ISSUE TITLE
[Documentation] Questionable constast, (some) red text is hard to read.

### ISSUE THREAD

**Issue by MrDodojo** [Mojang/ore-ui#8]
Text using the colour red e.g. --ifm-color-primary are hard to read.
Worst case is a `Code` tag inside an `A` link tag, 
![image](https://user-images.githubusercontent.com/47711280/139617749-dc66fbf5-d916-4fa1-8bad-cd417a585ad4.png)
which has a contrast score of 1.97, this is considered below minimum.

**Comment by pirelenito** [comment]
Thanks for submitting the issue ❤️

I just pushed a commit that should improve the contrast numbers. I'll close the issue, but feel free to re-open if you find anything I have missed.
